packages/uniforms-bootstrap3/README.md
packages/uniforms-bootstrap3/package.json
packages/uniforms-bootstrap3/src/components/fields/AutoField.js
packages/uniforms-bootstrap3/src/components/fields/BoolField.js
packages/uniforms-bootstrap3/src/components/fields/DateField.js
packages/uniforms-bootstrap3/src/components/fields/ErrorsField.js
packages/uniforms-bootstrap3/src/components/fields/FormGroup.js
packages/uniforms-bootstrap3/src/components/fields/ListAddField.js
packages/uniforms-bootstrap3/src/components/fields/ListDelField.js
packages/uniforms-bootstrap3/src/components/fields/ListField.js
packages/uniforms-bootstrap3/src/components/fields/ListItemField.js
packages/uniforms-bootstrap3/src/components/fields/LongTextField.js
packages/uniforms-bootstrap3/src/components/fields/NestField.js
packages/uniforms-bootstrap3/src/components/fields/NumField.js
packages/uniforms-bootstrap3/src/components/fields/RadioField.js
packages/uniforms-bootstrap3/src/components/fields/SelectField.js
packages/uniforms-bootstrap3/src/components/fields/SubmitField.js
packages/uniforms-bootstrap3/src/components/fields/TextField.js
packages/uniforms-bootstrap3/src/components/forms/AutoForm.js
packages/uniforms-bootstrap3/src/components/forms/BaseForm.js
packages/uniforms-bootstrap3/src/components/forms/QuickForm.js
packages/uniforms-bootstrap3/src/components/forms/ValidatedForm.js
packages/uniforms-bootstrap3/src/components/forms/ValidatedQuickForm.js
packages/uniforms-bootstrap3/src/index.js
packages/uniforms-bootstrap3/src/lib/gridClassName.js

http://puu.sh/p4cxx/c1efb92e85.png
http://puu.sh/p4cyd/9b51459c6f.png

added bootstrap3, port of bootstrap4

---

packages/uniforms-bootstrap3/src/components/fields/RadioField.js
packages/uniforms-bootstrap4/src/components/fields/RadioField.js
packages/uniforms-semantic/src/components/fields/RadioField.js
packages/uniforms-unstyled/src/components/fields/RadioField.js

fixes https://github.com/vazco/uniforms/issues/24

use also transform in radio-fields to display the label

---

packages/uniforms-bootstrap3/src/components/fields/BoolField.js
packages/uniforms-bootstrap4/src/components/fields/BoolField.js

The `modifyProps` function is just an idea, but easiest to communicate this way....

Dev issue 35 label left

---

packages/uniforms/src/components/fields/BaseField.js

fixes https://github.com/vazco/uniforms/issues/76

Check if scheme changed in BaseField.shouldComponentUpdate

---

packages/uniforms-bootstrap4/src/components/fields/ListAddField.js

https://github.com/twbs/bootstrap/issues/21014

Fixed bootstrap4 ListAddField styling

---

demo/lib/presets.js
packages/uniforms/src/GraphQLBridge.js
packages/uniforms/test/GraphQLBridge.js

... as requested!
My understanding of Uniforms and React is not deep.  So, more work may be required for this PR to be production ready.

Fix issue #183

---

packages/uniforms/src/GraphQLBridge.js
packages/uniforms/src/SimpleSchema2Bridge.js

Solution for "Unable to resolve some modules" warning - issue #196

Silence Meteor missing module warning

---

packages/uniforms-bootstrap4/src/LongTextField.js

For issue https://github.com/vazco/uniforms/issues/208

Pass down rows prop of LongTextField  to textarea input

---

demo/components/Application.js
demo/components/ApplicationPropsField.js
demo/main.css

Scope for demo app styles

---

packages/uniforms-antd/src/ListField.js
packages/uniforms-antd/src/ListItemField.js
packages/uniforms-antd/src/TextField.js
packages/uniforms-antd/src/wrapField.js

Allow labelCol and wrapperCol props on Form Item

---

demo/package.json
packages/uniforms-material/package.json

Updates the material-ui dependency to the latest version: material-ui 0.17.0

latest material-ui as dependency (closes #231)

---

demo/package.json
package.json

fix dependencies (for deploy demo)

---

packages/uniforms-antd/src/ListField.js
packages/uniforms-antd/src/NestField.js
packages/uniforms-antd/src/wrapField.js
packages/uniforms-bootstrap3/src/ListField.js
packages/uniforms-bootstrap3/src/NestField.js
packages/uniforms-bootstrap3/src/wrapField.js
packages/uniforms-bootstrap4/src/ListField.js
packages/uniforms-bootstrap4/src/NestField.js
packages/uniforms-bootstrap4/src/wrapField.js
packages/uniforms-material/src/DateField.js
packages/uniforms-material/src/LongTextField.js
packages/uniforms-material/src/NumField.js
packages/uniforms-material/src/SelectField.js
packages/uniforms-material/src/TextField.js
packages/uniforms-semantic/src/BoolField.js
packages/uniforms-semantic/src/DateField.js
packages/uniforms-semantic/src/ListField.js
packages/uniforms-semantic/src/LongTextField.js
packages/uniforms-semantic/src/NestField.js
packages/uniforms-semantic/src/NumField.js
packages/uniforms-semantic/src/RadioField.js
packages/uniforms-semantic/src/SelectField.js
packages/uniforms-semantic/src/TextField.js

Change inline Error to show errorMessage

---

API.md

Small docs update to reflect the code

`showInlineError` is available in 'material' too

---

packages/uniforms-bootstrap3/src/ErrorField.js
packages/uniforms-bootstrap4/src/ErrorsField.js

https://github.com/vazco/uniforms/issues/301#issuecomment-310292017

301 bootstrap errorsfield styling

---

packages/uniforms-bootstrap4/src/RadioField.js

note review this after #303 so the other commits don't cause problems (I would have rebased, but needed 	86e51ca )

304 radios need space

---

CHANGELOG.md
packages/uniforms-material/src/LongTextField.js

Fixing LongTextField wrong prop name

LongTextField placeholder => hintText

---

packages/uniforms-semantic/src/BoolField.js
packages/uniforms/src/GraphQLBridge.js

Refer to issue:
https://github.com/vazco/uniforms/issues/335

Add support for Boolean type in GraphQLBridge

---

packages/uniforms/__tests__/ValidatedForm.js
packages/uniforms/src/AutoForm.js
packages/uniforms/src/BaseForm.js
packages/uniforms/src/ValidatedForm.js

This PR i aimed to use setState with a function only, all across `uniforms` package.

Functional set state

---

INTRODUCTION.md

Intro update

---

demo/imports/components/ApplicationPreviewField.js
demo/imports/lib/presets.js
demo/imports/lib/schema.js
demo/package-lock.json
demo/package.json

This is a small enhancement which presents the usage of `JSONSchemaBridge` inside demo app.

Add JSON schema to demo app

---

packages/uniforms/src/SimpleSchemaBridge.js

Check 'Match' is defined as well as 'SimpleSchema'

---

packages/uniforms/src/filterDOMProps.js

Add `transform` to list of props to filter out

---

packages/uniforms-antd/src/wrapField.js

Making AutoField, and all other components enhanced via `wrapField`, customizable through a `style` prop.

AntD: Customizable style on AutoField

---

packages/uniforms-bootstrap3/src/LongTextField.js

Pass rows prop of LongTextField to textarea input bootstrap3

---

packages/uniforms-material/src/TextField.js

Explicitly pass type prop in TextField component

---

INTRODUCTION.md

Edit not worked link to Bridge.js

---

README.md

Use the official wording :)

---

demo/imports/lib/presets.js

Fix JSONSchema example inside uniforms demo project

---

demo/imports/components/Application.js
demo/imports/lib/utils.js

Save demo state into url hash

---

demo/imports/lib/utils.js

Tweak demo state persitance changes

---

packages/uniforms/__tests__/AutoForm.js

referes to https://github.com/vazco/uniforms/issues/457

more tests for reset

---

packages/uniforms-material/__tests__/wrapField.js
packages/uniforms-material/src/BoolField.js
packages/uniforms-material/src/DateField.js
packages/uniforms-material/src/ErrorField.js
packages/uniforms-material/src/ErrorsField.js
packages/uniforms-material/src/ListAddField.js
packages/uniforms-material/src/NestField.js
packages/uniforms-material/src/RadioField.js
packages/uniforms-material/src/SelectField.js
packages/uniforms-material/src/wrapField.js

Fixes: #495 
Introduces `wrapField` helper to reduce code duplication. This is similar to other packages.

Add ability to pass variant prop to FormControl. Fixes #495

---

packages/uniforms/__tests__/JSONSchemaBridge.js
packages/uniforms/src/JSONSchemaBridge.js

Added top level $ref suppport in JSONSchemaBridge.

---

packages/uniforms-material/__tests__/SelectField.js
packages/uniforms-material/src/SelectField.js

Fix SelectField required state. Fixes #512

---

packages/uniforms/src/BaseField.js
packages/uniforms/src/BaseForm.js

With this change, each field (any nested component in general) can trigger a submit.

Added onSubmit to the context.

---

docs/components/GuestForm5.js
docs/components/GuestForm6.js
docs/components/GuestForm7.js
docs/components/GuestSchema.js
docs/components/GuestSchema2.js
docs/tutorials-basic-uniforms-usage.mdx
docs/tutorials-customizing-your-form-layout.mdx
docs/tutorials-using-predefined-fields.mdx
website/sidebars.json

New docs tutorial 3rd chapter

---

package.json
packages/uniforms-bridge-graphql/__tests__/index.js
packages/uniforms-bridge-graphql/src/index.js
packages/uniforms-bridge-json-schema/__tests__/index.js
packages/uniforms-bridge-json-schema/src/index.js
packages/uniforms-bridge-simple-schema-2/__tests__/index.js
packages/uniforms-bridge-simple-schema-2/src/index.js
packages/uniforms-bridge-simple-schema/__tests__/index.js
packages/uniforms-bridge-simple-schema/src/index.js

Added default export of bridges

---

website/components/Home/Examples.js

There were unintended indents at section 'Simple, yet powerful'.

Fixed indentation of code listings on landing page

---

website/components/Home/CallToAction/CallToAction.module.css
website/components/Home/CallToAction/index.js
website/components/Home/index.js

Call to action

---

website/components/LandingPage/index.js
website/components/LandingPage/index.module.css

Fixed top padding when entering docs.

---

website/docusaurus.config.js
website/plugins/docusaurus-plugin-hotjar/package.json
website/plugins/docusaurus-plugin-hotjar/src/hotjar.js
website/plugins/docusaurus-plugin-hotjar/src/index.js

- Added hotjar plugin for docusaurus
- Configured for company use cases

Add hotjar

---

docs/tutorials-creating-custom-theme.md
website/sidebars.json

This pull request solves #636 by adding a section about creating custom themes for uniforms based on using default themes.

Added section about creating custom theme (#636).

---

CHANGELOG.md
docs/examples-custom-fields.mdx
docs/examples/CustomFields/RatingField.js
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts
packages/uniforms/__tests__/randomIds.ts

Array initialization problems, same as in #643.

Fixed array initialization (fixes #656).

---

website/components/LandingPage/Header.js
website/components/LandingPage/OpenSource.js

Fix header content & github badges

---

docs/motivation.md
docs/why-are-uniforms.md
website/components/LandingPage/ExampleSimpleYetPowerful.js

docs: extendability -> extensibility

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

Fixed unexpected behavior described in #722.
Closes #722.

Added JSONSchemaBridge getField resolve to $ref definition inside allOf.

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

Add JSON Schema properties: `maxCount`, `minCount`, `max`, `min`, `step`.

Add missing JSON Schema properties (closes #748).

---

website/index.module.css
website/pages-parts/LandingPage/CommercialServices.tsx
website/pages-parts/LandingPage/LandingPage.tsx

This PR will add a new section on the uniforms.tools website.

Add Commercial Services section on the website

---

package-lock.json
package.json
website/package.json

Updated Docusaurus dependencies to current version (stable) - `2.0.0-alpha.69`.

Updated Docusaurus dependencies.

---

docs/examples-custom-fields.mdx

Removed 'ensureValue' from CustomAutoField example

---

docs/api-forms.md
docs/migrating-2-to-3.md

Fixed documentation of "onValidate"

---

website/pages-parts/LandingPage/CommercialServices.tsx

Change at the request from Marcin Pędziwiatr.

Changed link in CommercialServices in website.

---

CHANGELOG.md
packages/uniforms-antd/__tests__/NumField.tsx
packages/uniforms-bootstrap3/__tests__/NumField.tsx
packages/uniforms-bootstrap4/__tests__/NumField.tsx
packages/uniforms-material/__tests__/NumField.tsx
packages/uniforms-material/src/NumField.tsx
packages/uniforms-semantic/__tests__/NumField.tsx
packages/uniforms-unstyled/__tests__/NumField.tsx

This change fixes #855 and adds tests for it across all themes.

Fixed missing step prop NumField (fixes #855).

---

packages/uniforms-antd/src/SelectField.tsx
packages/uniforms-bootstrap3/__tests__/SelectField.tsx
packages/uniforms-bootstrap3/src/SelectField.tsx
packages/uniforms-bootstrap4/__tests__/SelectField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx
packages/uniforms-material/__tests__/SelectField.tsx
packages/uniforms-semantic/__tests__/SelectField.tsx
packages/uniforms-semantic/src/SelectField.tsx
packages/uniforms-unstyled/__tests__/SelectField.tsx
packages/uniforms-unstyled/src/SelectField.tsx

Add multiselect feature for select input.

Add Multiselect (closes #737)

---

packages/uniforms-antd/src/BaseForm.tsx

Added Form layout configuration prop in AntD package. It can handle two values - `horizontal` and `vertical` according to [Form documentation](https://ant.design/components/form/#API).

Added Form layout configuration prop in uniforms-antd (closes #861).

---

docs/api-helpers.md

This change documents the `kind` option of the `connectField` HOC.

Documented kind option of connectField (closes #878).

---

docs/uth-autofield-algorithm.md

This change documents customizing `AutoField`.

Documented customizing AutoField (closes #879).

---

packages/uniforms-antd/__tests__/_createContext.ts
packages/uniforms-bootstrap3/__tests__/_createContext.ts
packages/uniforms-bootstrap4/__tests__/_createContext.ts
packages/uniforms-material/__tests__/_createContext.ts
packages/uniforms-semantic/__tests__/_createContext.ts
packages/uniforms-unstyled/__tests__/_createContext.ts
packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/__tests__/ValidatedForm.tsx
packages/uniforms/__tests__/connectField.tsx
packages/uniforms/src/BaseForm.tsx
packages/uniforms/src/ValidatedForm.tsx
packages/uniforms/src/types.ts

see https://github.com/vazco/uniforms/issues/889
fixes https://github.com/vazco/uniforms/issues/889

feat: submitted state in context 

---

docs/api-bridges.md
docs/api-helpers.md

This change improves helper docs and closes #905.

Improved helpers docs.

---

package-lock.json
package.json
reproductions/package-lock.json
reproductions/package.json
website/package.json

(Related with #923 and #925)
While working on #925 I had to update the Ajv version to test this change, but since I wasn't sure if we really want this update in uniforms I decided to introduce this PR and ask you for your opinion.

Updated ajv version in reproductions and website.

---

.github/workflows/CI.yml

Added future-LTS and the current version of node (16)  to GitHub CI workflow.

Add node 16 to CI workflow.

---

docs/api-bridges.md

Added short description about `GraphQLSchemaBridge` in docs and extended the code example.

Extended GraphQLSchemaBridge documentation.

---

packages/uniforms/__tests__/changedKeys.ts
packages/uniforms/src/changedKeys.ts

added typeOf valueA and valueB for changedKeys
PR for https://github.com/vazco/uniforms/issues/982#issuecomment-898503298

Added support for changing value type in changedKeys (fixes #982).

---

docs/examples-custom-fields.mdx

I've also checked in path for other links to our code to see if any other link is broken but this is the only one that I found.

Fixed link in custom field documentation.

---

website/index.module.css

Added dark theme support to the playground toolbar.

Fix dark theme on uniforms playground (dropdowns are illegible)

---

website/index.module.css

Fixed playground toolbar's dark theme.

Fix dark theme on uniforms playground - select options

---

package-lock.json
package.json
website/docusaurus.config.js
website/package.json
website/plugins/docusaurus-plugin-hotjar/package.json

In this PR I've updated Docusaurus and updated the configuration of the Algolia search to fix #1095.

Updated Docusaurus (fixes #1095).

---

website/docusaurus.config.js
website/index.module.css
website/pages-parts/LandingPage/LandingPage.tsx

Adding new button `Enterprise` to navigation bar that links to "Commercial support - Form Builder" section with smooth scroll animation.

Added "Enterprise" button in docs navigation

---

packages/uniforms-material/__tests__/SelectField.tsx
packages/uniforms-material/src/SelectField.tsx

In this pull request, the correct type definitions have been added to the SelectField (material) component

Improved SelectField typings in uniforms-material

---

reproductions/package.json

Fixes #1144 
Example: https://codesandbox.io/s/sad-agnesi-vg3t1s

Added missing peerdeps as dependencies to reproductions.

---

packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts

Hey
It's my first PR for this project. The goal is to support GraphQL Enum values.
Thanks for checking it.

Support GraphQL Enums and show them as dropdown

---

.github/labeler.yml
.husky/pre-commit
.huskyrc.json
package-lock.json
package.json

- update Husky to v8.0.1
- delete lint-stage from package.json
- use npx lint-staged as suggested in this [issue](https://github.com/typicode/husky/issues/949)

Update Husky and Lint Staged

---

.github/CODEOWNERS

Added @wadamek65 to CODEOWNERS.

Added @wadamek65 to CODEOWNERS.

---

packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts

Hotfix for new SimplSchema version and it's bridge based on https://github.com/vazco/uniforms/issues/1189

Added compatibility layer to Simple Schema v3 (closes #1189)

---

packages/uniforms-bootstrap5/__tests__/TextField.tsx
packages/uniforms-bootstrap5/src/TextField.tsx

Kindly review it for #1223 
If any additional changes are required, please let me know.

Handled minLength and maxLength (closes #1223).

---

website/lib/stats.ts

This PR fixes the number of downloads displayed on the `uniforms` website.

Fix package downloads

---

website/pages-parts/LandingPage/Footer.tsx

The year in the footer has been updated to be dynamic using the `new Date().getFullYear()`.

Changed year on the footer in docs

---

website/lib/presets.ts

This is a fix for the playground errors on the uniforms.tools website that occurred due to changes in the bridge's constructor parameters.

Fix playground bridge constructor options

---

.github/workflows/CI.yml
package-lock.json
package.json
reproductions/package.json

Node 20 is a current Node release, and our newest version (Node 18) loses its LTS status in 4 months.

Add Node 20 to the CI workflow, move building docs to Node 20

---

.github/CODEOWNERS
.github/workflows/CI.yml

Add possibility to manually dispatch CI actions.

Add workflow_dispatch

---

website/docs/examples/multi-step-form.mdx

- added multi step form example to docs
- it is based on the first option suggested in the current FAQ ([link](https://uniforms.tools/docs/faq/#how-can-i-create-a-multi-step-form))

Added multi step form example to docs
