vazco/uniforms

packages/uniforms/src/components/fields/BaseField.js

I split this off of PR #38 - so it was easier to merge (seems like a super-simple upstream)
(In my case, I'm using an icon in a label)

Add proptype support for JSX, react node, as label

---

packages/uniforms-semantic/src/components/fields/DateField.js
packages/uniforms-semantic/src/components/fields/NumField.js
packages/uniforms-semantic/src/components/fields/TextField.js
packages/uniforms-semantic/test/combined.js

Adds ability to use icons in `TextField` component.
Example usage:
```javascript
<TextField name="username" icon="user" />
<TextField name="query" iconLeft="search" />
```
There could be only one icon, and `icon` take precedence before `iconLeft`.
I could also add support for [pointer events](http://semantic-ui.com/elements/input.html#icon) if you think it would useful:
```javascript
<TextField name="username" icon="add user" onIconClick={() => {}} />
```
One problem I'm aware of is that adding `ui icon input` classes change the input width.
This could be solved by adding `fluid` class either by `TextField` itself (IMHO bad idea) or end user:
```javascript
<TextField name="username" className="fluid" icon="user" />
```

SemanticUI: Add support for input icons

---

packages/uniforms-bootstrap3/src/components/fields/FormGroup.js
packages/uniforms-bootstrap4/src/components/fields/FormGroup.js

If true, we could include the error message as a text block with the input form.
This seems like a very useful option,
especially for forms where the errors are not rendered.

An idea for `showInlineError` Boolean

---

packages/uniforms/package.json
packages/uniforms/src/bridges/SimpleSchema2Bridge.js

Some fixes required to get the new SimpleSchema2 bridge working after updating to [v1.1.1](https://github.com/vazco/uniforms/tree/v1.1.1)

Enable SimpleSchema2Bridge with simpl-schema package

---

packages/uniforms-bootstrap4/src/components/fields/ListAddField.js
packages/uniforms-bootstrap4/src/components/fields/ListDelField.js
packages/uniforms-bootstrap4/src/components/fields/ListField.js
packages/uniforms-bootstrap4/src/components/fields/ListItemField.js

Add ability to include custom add / remove icons for ListFields.
This can be implemented in either AutoField or by using ListField.
Example AutoField:
```
<AutoField
name="athletics.otherSports"
addIcon={(<i className="fa fa-add-circle" />)}
removeIcon={(<i className="fa fa-close-circle" />)}
/>
```
Example ListField:
```
<ListField
name="athletics.otherSports"
addIcon={(<i className="fa fa-add-circle" />)}
removeIcon={(<i className="fa fa-close-circle" />)}
>
<ListItemField name="$">
<NestField>
<TextField name="sportName" className="col-md-6" />
<TextField name="yearsParticipated" className="col-md-6" />
</NestField>
</ListItemField>
</ListField>
```

custom addIcon and removeIcon for ListFields for bootstrap-4

---

packages/uniforms-bootstrap3/src/components/fields/ListAddField.js
packages/uniforms-bootstrap3/src/components/fields/ListDelField.js
packages/uniforms-bootstrap3/src/components/fields/ListField.js
packages/uniforms-bootstrap3/src/components/fields/ListItemField.js

Add ability to include custom add / remove icons for ListFields.
This can be implemented in either AutoField or by using ListField.
Example AutoField:
```
<AutoField
name="athletics.otherSports"
addIcon={(<i className="fa fa-add-circle" />)}
removeIcon={(<i className="fa fa-close-circle" />)}
/>
```
Example ListField:
```
<ListField
name="athletics.otherSports"
addIcon={(<i className="fa fa-add-circle" />)}
removeIcon={(<i className="fa fa-close-circle" />)}
>
<ListItemField name="$">
<NestField>
<TextField name="sportName" className="col-md-6" />
<TextField name="yearsParticipated" className="col-md-6" />
</NestField>
</ListItemField>
</ListField>
```

custom addIcon and removeIcon for ListFields for bootstrap-3

---

packages/uniforms-bootstrap3/src/components/fields/SelectField.js
packages/uniforms-bootstrap4/src/components/fields/SelectField.js
packages/uniforms-semantic/src/components/fields/SelectField.js
packages/uniforms-unstyled/src/components/fields/SelectField.js

Reference Issue: #119 
Tested with optional, required, with and without placeholders. Also tested with Nested objects and arrays of objects.
If this looks acceptable, I will commit more to this PR/branch for the other 3 UI packages.

Allow deselection of optional SelectField

---

packages/uniforms/src/components/forms/AutoForm.js

fixes https://github.com/vazco/uniforms/issues/140
however, something is odd:
In the demo, the form already contains default-values. not from the mode, but from the bridge/schema.
reset does not seem to restore these default-values and i am unsure whether this should be the case.

reset sets model back to initial model

---

packages/uniforms/src/connectField.js

Currently there is no way set default value for SelectField, because its value by default is `''` (empty string) which is not equal to `undefined`.

Fix initialValue check

---

packages/uniforms-bootstrap4/src/BoolField.js
packages/uniforms-bootstrap4/src/RadioField.js
packages/uniforms-bootstrap4/src/gridClassName.js
packages/uniforms-bootstrap4/src/wrapField.js

Bootstrap has changed a few classes to support flexbox
form-control-label  --> col-form-label (required)
col-{size}-{number} --> col-{number}  (optional)
I have maintained backwards compatibility
But should eventually clean it up and remove later.
Bootstrap has changed a few classes on check/radio 
radio & radio-inline --> form-check
<label>              --> form-check-label
<input>              --> form-check-input
checkbox & checkbox-inline --> form-check
<label>                    --> form-check-label
<input>                    --> form-check-input

bootstrap 4 alpha.6 changed classes

---

API.md
packages/uniforms-material/src/BoolField.js
packages/uniforms-material/test/combined.js

This PR adds an appearance property to BoolField that allows rendering as a Toggle if appearance set to 'toggle'.  Default or any other value is 'checkbox' (present behavior) so as to not break any existing apps.
That is, ```<BoolField name='field' />``` still works as it previously did by rendering a checkbox, but now you can alternatively use toggles: ```<BoolField name='field' appearance='toggle' />```
Updated combined tests for the above (x35)
NOTE: I did **not** update any package version numbers.

Allows material BoolFields to be checkboxes or toggles

---

packages/uniforms-material/src/SelectField.js

Solves #236 
Wondering if i may do something like this to avoid triple field type checking:
```js
const renderSelect = ({
...props
}, context, multiple = props.fieldType === Array) => {
/* Rendering */
}
```
What do you think about this?

Support multiple on material ui SelectField

---

API.md
packages/uniforms-material/src/DateField.js

Solves #246 
Yet don't know what to do with the following: `DateTimeFormat`, `locale` and `formatDate`. Just passing them down to the right component so far. Formatting solution from DatePicker in material-ui doesn't support time at all so we probably can't use it. Shall we create own solution or leave it as it is right now, not allowing to format date string in DateField?

Split unhandled props into DatePicker or TimePicker

---

packages/uniforms/package.json

Fixes the below warnings when using `graphql@0.10.1` and `simpl-schema@0.3.0`.
Will allow others to use the latest version of `graphql` or `simpl-schema` up to `v1.0.0` without incurring the below warnings.
```
npm WARN uniforms@1.18.1 requires a peer of graphql@^0.8.2 || ^0.9.1 but none was installed.
npm WARN uniforms@1.18.1 requires a peer of simpl-schema@^0.2.0 || ^0.1.0 || ^0.0.4 but none was installed.
```

peerDependencies to allow for newer versions

---

packages/uniforms-semantic/src/BoolField.js
packages/uniforms/src/GraphQLBridge.js

Fix for https://github.com/vazco/uniforms/issues/338

BoolField inline error position correction

---

packages/uniforms-antd/__tests__/TextField.js
packages/uniforms-antd/src/TextField.js

Should fix #345 
@radekmie Let me know if this PR is okay.
I didn't see a need to touch `filterDOMProps` especially since its being used by all other style versions. It seems it was just a missed prop.

Fix TextField type prop for antd  (closes #345)

---

packages/uniforms-antd/__tests__/BoolField.js
packages/uniforms-antd/src/BoolField.js
packages/uniforms/src/filterDOMProps.js

PR adds ability to create an antd `Checkbox` with uniforms `BoolField` instead of just the antd `Switch`.
```javascript
<BoolField
checkbox
name="myCheckbox"
label="Check here if you agree"
/>
```

added checkbox option for BoolField for antd

---

API.md
packages/uniforms-semantic/__tests__/DateField.js
packages/uniforms-semantic/__tests__/NumField.js
packages/uniforms-semantic/__tests__/TextField.js
packages/uniforms-semantic/src/DateField.js
packages/uniforms-semantic/src/NumField.js
packages/uniforms-semantic/src/TextField.js

Adding support for `wrapClassName` in SUI theme, similar solution already exists in Bootstrap3/4 themes.
This will allow to use Semantic inputs variants like size, inverted, transparent etc.

Added support for wrapClassName in SemanticUI theme

---

CHANGELOG.md
packages/uniforms/__tests__/ValidatedForm.js
packages/uniforms/src/BaseForm.js
packages/uniforms/src/ValidatedForm.js

This PR aims to do two things:
- **Change:** If `onSubmit` rejects, it's treated as a form error.
This is an old-standing idea, for few months on roadmap already. Also reported in #341. The goal is to change this code:
```js
<ValidatedForm
error={this.state.error}
schema={schema}
onSubmit={model => db.submitThatReturnsPromise(model)}
onSubmitFailure={error => this.setState({error})}
onSubmitSuccess={() => this.setState({error: null})}
/>
```
Into to this code:
```js
<ValidatedForm
schema={schema}
onSubmit={model => db.submitThatReturnsPromise(model)}
/>
```
Nice, huh?
- **Fix:** `form.submit` correctly rejects on validation error.
It's an important fix; it was mentioned already in #331.

Changed onSubmit rejection meaning.

---

demo/imports/lib/styles.js
packages/uniforms-bootstrap4/__tests__/BoolField.js
packages/uniforms-bootstrap4/__tests__/ErrorsField.js
packages/uniforms-bootstrap4/__tests__/RadioField.js
packages/uniforms-bootstrap4/__tests__/gridClassName.js
packages/uniforms-bootstrap4/src/BoolField.js
packages/uniforms-bootstrap4/src/DateField.js
packages/uniforms-bootstrap4/src/ErrorField.js
packages/uniforms-bootstrap4/src/ErrorsField.js
packages/uniforms-bootstrap4/src/ListAddField.js
packages/uniforms-bootstrap4/src/ListField.js
packages/uniforms-bootstrap4/src/ListItemField.js
packages/uniforms-bootstrap4/src/LongTextField.js
packages/uniforms-bootstrap4/src/NumField.js
packages/uniforms-bootstrap4/src/RadioField.js
packages/uniforms-bootstrap4/src/SelectField.js
packages/uniforms-bootstrap4/src/SubmitField.js
packages/uniforms-bootstrap4/src/TextField.js
packages/uniforms-bootstrap4/src/gridClassName.js
packages/uniforms-bootstrap4/src/wrapField.js

Becouse the bootstrap released the final stable 4 version i decided to update `uniforms-bootstrap4` from alpha-5 to version 4.0.0. I tested mostly on `demo` app and tried to keep similar appearance and behaviour like with alpha version. I tested also with some more complicated schemas  and imho looks good, but maybe something i missed so i will be happy on every review or remark.

Update bootstrap to v4.0.0

---

packages/uniforms/src/filterDOMProps.js

When using the `AutoField` (and this can be done indirectly
via `AutoFields`), it is possible for `allowedValues` to be
passed from the `props` to the underlying DOM element.
In such a case, a runtime warning will be triggered:
React does not recognize the `allowedValues` prop on a DOM element
A summary of the component stack:
in input (created by Input)
in Input (created by Text)
...
in Text (created by TextField)
in TextField (created by AutoField)
To silence this warning, `filterDOMProps` has been updated to
exclude `allowedValues` from being passed to the underlying
DOM element.
This commit does not deal with package versioning.
Resolves #389
---
Small example to replicate the warning: https://codesandbox.io/s/xwy15nn0o

Add `allowedValues` to `filterDOMProps`

---

packages/uniforms-antd/src/wrapField.js

Since the "style" prop is affected by a serious issues (see https://github.com/vazco/uniforms/pull/404#issuecomment-383139892), I updated the prop name into "wrapperStyle".
This PR fixes #414

Fixes Pull Request #404 using wrapperStyle

---

packages/uniforms/__tests__/GraphQLBridge.js
packages/uniforms/__tests__/JSONSchemaBridge.js
packages/uniforms/src/GraphQLBridge.js
packages/uniforms/src/JSONSchemaBridge.js

Handle field placeholder when labels disabled

---

packages/uniforms-antd/src/wrapField.js

When using uniforms-and, The prop wrapperStyle is not being recognized, due to the fact that is not filtered out, in wrapField.js file.

wrapperStyle prop not filtered out in uniforms antd

---

packages/uniforms/__tests__/GraphQLBridge.js
packages/uniforms/src/GraphQLBridge.js

The internal type stored in `GraphQLNonNull` was never extracted as the whole `field` needs to be passed according to `extractFromNonNull` definition.

Fix extracting the type from GraphQLNonNull in getProps

---

packages/uniforms/__tests__/ValidatedForm.js

While looking to test my upcoming changes to #441, I got a bit carried away trying to make sense of the `ValidatedForm` tests. I have refactored them in a way that highlights the patterns and makes it clear to me what my new tests should look like. Hopefully that holds true in general.
There was one of the tests that I couldn't get to the bottom of, as described initially in fa4dc6b. What do you think?
The real history is available [here](https://github.com/BudgieInWA/uniforms/compare/submitting-state-1...validated-form-tests) for the curious.

Refactor ValidatedForm tests

---

API.md
packages/uniforms-material/src/DateField.js
packages/uniforms-material/src/SelectField.js

Addresses #481. 
It turns out there was only `DateField` and `SelectField` that can use the extra `labelProps`. The `TextField` component, used in most places, can already get a `InputLabelProps` prop that will be passed to its `InputLabel`.
For the sake of consistency, I changed the `FormLabel` to `InputLabel` on `DateField`, as I don't think it is required. I'll revert it if there was a specific reason behind it.

Pass labelProps to DateField and SelectField

---

packages/uniforms/__tests__/JSONSchemaBridge.js
packages/uniforms/src/JSONSchemaBridge.js

JSON schema convention uses "title": on a property to specify a human-friendly label.  
This PR tries to use this title when label:true, before falling back to fieldNameCapitalized()

Uses the common JSON Schema "title" property as the default field label when it exists

---

packages/uniforms-material/package.json
packages/uniforms-material/src/SubmitField.js

Material-ui has started throwing warnings when using the old `raised` variant.

Stop using deprecated "raised" variant, use "contained" instead

---

packages/uniforms-material/src/BoolField.js
packages/uniforms-material/src/DateField.js
packages/uniforms-material/src/RadioField.js
packages/uniforms-material/src/SelectField.js
packages/uniforms-material/src/wrapField.js

This PR introduces `wrapField.filterDOMProps` and `wrapField.filterDOMPropsList` in `uniforms-material` theme. Usage is the same as for `filterDOMProps` - if you use `wrapField`, then filter your props to get rid of these used in that helper.
Questions:
* Is the name OK? I'm especially concerned about the `filterDOMPropsList`.
* Should we make it public or prefix it with an underscore and treat it as an implementation detail?
* Should we introduce such logic in other themes for compatibility?

Added wrapField.filterDOMProps in uniforms-material (fixed #501).

---

API.md
packages/uniforms-material/__tests__/SelectField.js
packages/uniforms-material/src/BoolField.js
packages/uniforms-material/src/DateField.js
packages/uniforms-material/src/ErrorField.js
packages/uniforms-material/src/ErrorsField.js
packages/uniforms-material/src/ListAddField.js
packages/uniforms-material/src/LongTextField.js
packages/uniforms-material/src/NestField.js
packages/uniforms-material/src/NumField.js
packages/uniforms-material/src/RadioField.js
packages/uniforms-material/src/SelectField.js
packages/uniforms-material/src/TextField.js

Multiple improvements for uniforms-material package

---

packages/uniforms-material/package.json

I would like to enable a third-party component search for Material-UI components like Gatsby is doing it with its plugins page: https://www.gatsbyjs.org/plugins/.

Add material-ui to the list of npm keywords

---

packages/uniforms/src/QuickForm.js

With this change, using a different form component can override only `BaseForm.render`, instead of both `BaseForm` and `QuickForm`.

Simplified QuickForm rendering

---

packages/uniforms-bridge-graphql/src/GraphQLBridge.js

Hi,
when you try to create labels for nested arrays in a schema the replacement code broke. Setting the regex replacement to global fixes it. 
This did not work prior to the fix since only the first index, in this case, the `0` is replaced - the second `3` is not touched.
` .getProps("arrayFieldA.0.innerArray.3.description")`
but works after the fix.

Nesting Arrays breaks props from schemaMetadata

---

docs/api-fields.md
packages/uniforms-bootstrap3/__tests__/wrapField.js
packages/uniforms-bootstrap3/src/wrapField.js
packages/uniforms-bootstrap4/__tests__/wrapField.js
packages/uniforms-bootstrap4/src/wrapField.js

For being able to alter the looks of the label without depending on 'grid'.

Add support for label classes

---

docs/api-fields.md
packages/uniforms-antd/__tests__/wrapField.js
packages/uniforms-antd/src/wrapField.js

Here's a quick pull request to add support for the "help" prop on a field when using the antd theme. 
I'm switching a project from bootstrap to antd and discovered this feature was missing for antd.  Seemed like the best fix was to map the help prop to the "extra" prop on the antd Form.Item component.

Antd help prop

---

packages/uniforms-antd/src/BoolField.js

Fix deprecated icon warning in the antd theme: "Warning: [antd: Icon] Icon 'cross' is typo and depracated, please use 'close' instead."

Fix deprecated icon warning in antd theme

---

packages/uniforms-bootstrap3/__tests__/NumField.js
packages/uniforms-bootstrap3/src/NumField.js
packages/uniforms-bootstrap4/__tests__/NumField.js
packages/uniforms-bootstrap4/src/NumField.js
packages/uniforms-material/__tests__/NumField.js
packages/uniforms-material/src/NumField.js
packages/uniforms-semantic/__tests__/NumField.js
packages/uniforms-semantic/src/NumField.js
packages/uniforms-unstyled/__tests__/NumField.js
packages/uniforms-unstyled/src/NumField.js
packages/uniforms/__tests__/connectField.js

A long time ago, back in #167, I had implemented special handling of numeric inputs in `NumField` because it behaved weirdly in most browsers (it was crazy in Safari). It got fixed by React in version 16, but the mechanism stayed as it was, because of backward compatibility. Now, it stung back in #558. I've decided to make it logic conditional, to enable it only in React versions which needs them.

Made NumField adaptive to React version

---

CHANGELOG.md
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.js
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.js

The previous implementation was not able to parse `dataPaths` with array indexes (`.a[0]`) and escapes (`.a['b-c']`). Now it works correctly, even when the `jsonPointers` flag is enabled (`/a/0` and `/a/b-c`).

Fixed dataPath parsing (fixes #593).

---

website/components/LandingPage/ExampleSimpleYetPowerful.js

This PR fixes a typo in the landing page - it changes `Abbrevates from code by 51%` to `Abbreviates form code by 51%`.

Fixed typo in the landing page.

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.js
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.js

[As @ziedmahdi noticed](https://github.com/vazco/uniforms/issues/345#issuecomment-535979999), using `uniforms: { type: 'password' }` in JSON schema had no effect.

Fixed JSON schema type conflict.

---

.eslintignore
.gitignore
.prettierignore
packages/uniforms-antd/package.json
packages/uniforms-antd/tsconfig.es6.json
packages/uniforms-bootstrap3/package.json
packages/uniforms-bootstrap3/tsconfig.es6.json
packages/uniforms-bootstrap4/package.json
packages/uniforms-bootstrap4/tsconfig.es6.json
packages/uniforms-bridge-graphql/package.json
packages/uniforms-bridge-graphql/tsconfig.es6.json
packages/uniforms-bridge-json-schema/package.json
packages/uniforms-bridge-json-schema/tsconfig.es6.json
packages/uniforms-bridge-simple-schema-2/package.json
packages/uniforms-bridge-simple-schema-2/tsconfig.es6.json
packages/uniforms-bridge-simple-schema/package.json
packages/uniforms-bridge-simple-schema/tsconfig.es6.json
packages/uniforms-material/package.json
packages/uniforms-material/tsconfig.es6.json
packages/uniforms-semantic/package.json
packages/uniforms-semantic/tsconfig.es6.json
packages/uniforms-unstyled/package.json
packages/uniforms-unstyled/tsconfig.es6.json
packages/uniforms/package.json
packages/uniforms/tsconfig.es6.json
tsconfig.build.json
tsconfig.json

We've added separate compilation target for ES6 standard which enables classes.
We would like to ask @macrozone @refactorized to check if everything works fine.
1. Clone this branch.
2. Run `npm ci`.
3. Copy built files directly into `node_modules` to check if it works.

Added ES6 targets (closes #433).

---

packages/uniforms-antd/src/AutoForm.tsx
packages/uniforms-antd/src/BaseForm.tsx
packages/uniforms-antd/src/QuickForm.tsx
packages/uniforms-antd/src/ValidatedForm.tsx
packages/uniforms-bootstrap3/src/AutoForm.tsx
packages/uniforms-bootstrap3/src/BaseForm.tsx
packages/uniforms-bootstrap3/src/QuickForm.tsx
packages/uniforms-bootstrap3/src/ValidatedForm.tsx
packages/uniforms-bootstrap4/src/AutoForm.tsx
packages/uniforms-bootstrap4/src/BaseForm.tsx
packages/uniforms-bootstrap4/src/QuickForm.tsx
packages/uniforms-bootstrap4/src/ValidatedForm.tsx
packages/uniforms-material/src/AutoForm.tsx
packages/uniforms-material/src/BaseForm.tsx
packages/uniforms-material/src/QuickForm.tsx
packages/uniforms-material/src/ValidatedForm.tsx
packages/uniforms-semantic/src/AutoForm.tsx
packages/uniforms-semantic/src/BaseForm.tsx
packages/uniforms-semantic/src/QuickForm.tsx
packages/uniforms-semantic/src/ValidatedForm.tsx
packages/uniforms-unstyled/src/AutoForm.tsx
packages/uniforms-unstyled/src/BaseForm.tsx
packages/uniforms-unstyled/src/QuickForm.tsx
packages/uniforms-unstyled/src/ValidatedForm.tsx
packages/uniforms/src/AutoForm.tsx
packages/uniforms/src/BaseForm.tsx
packages/uniforms/src/QuickForm.tsx
packages/uniforms/src/ValidatedForm.tsx

As reported in #617, `AutoForm` (other form components too) have non-JSX compatible types. With this change base class (`Component`) and mixin helpers are preserved. It's not an ideal solution but it'll do for now. In the future, we'd have to define `BaseForm` generic type and other forms should simply derive from it, reusing generics.

Fixed preservation of mixin types (fixes #617).

---

.github/workflows/CI.yml

Codecov Action has a bug that results in incorrect reporting of non-`master` coverage. This change uses [codecov/codecov-bash](https://github.com/codecov/codecov-bash) directly, which is easier to maintain and significantly faster (no docker image is being built at the beginning of each run).
The bash script has the same bug _now_, as the code is already merged but wasn't released yet: https://github.com/codecov/codecov-bash/issues/169

Fixed branch test coverage reporting.

---

packages/uniforms-material/src/NumField.tsx

This change fixes #631 - how default props are assigned to `NumField`. There was a bug that the `defaultProps` were set on a helper function, not the component itself.

Fixed Material-UI NumField defaultProps handling (fixes #631).

---

docs/examples/CustomFields/RatingField.js

Fixes a problem with `RatingField` example in the documentation (the field isn't rendered).

Fixed RatingField example in docs

---

docs/api-helpers.md

Fixes a little inconsistency between `joinName`'s description and examples.

Fixed documentation of 'joinName' function

---

docs/examples/CommonForms/ShippingSchema.js
website/components/LandingPage/Header.js

Added `defaultValue: false` to `useThisAddressForPaymentDetails` field

Made "Use this address for payment details?" field in form example on the landing page optional

---

packages/uniforms-bootstrap3/__tests__/RadioField.tsx
packages/uniforms-bootstrap3/__tests__/SelectField.tsx
packages/uniforms-bootstrap3/src/RadioField.tsx
packages/uniforms-bootstrap3/src/SelectField.tsx
packages/uniforms-bootstrap4/__tests__/RadioField.tsx
packages/uniforms-bootstrap4/__tests__/SelectField.tsx
packages/uniforms-bootstrap4/src/RadioField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx
packages/uniforms-material/__tests__/SelectField.tsx
packages/uniforms-material/src/SelectField.tsx
packages/uniforms-semantic/__tests__/RadioField.tsx
packages/uniforms-semantic/__tests__/SelectField.tsx
packages/uniforms-semantic/src/RadioField.tsx
packages/uniforms-semantic/src/SelectField.tsx
packages/uniforms-unstyled/__tests__/RadioField.tsx
packages/uniforms-unstyled/__tests__/SelectField.tsx
packages/uniforms-unstyled/src/RadioField.tsx
packages/uniforms-unstyled/src/SelectField.tsx

This pull request fixes #671 by escaping select item names with its base64 encoding.

Correct attribute id format (fixes #671).

---

packages/uniforms-semantic/__tests__/BoolField.tsx
packages/uniforms-semantic/src/BoolField.tsx

This pull request fixes #680 and #681 by introducing `wrapClassName` prop into `BoolField` and logic for adding _fitted_ class name  if `label` prop is falsy (instead of only if `label` is `undefined`, not passed). This last functionality differs from the one specified [here](https://react.semantic-ui.com/modules/checkbox/#variations-fitted).

Update semantic BoolField (fixes #680, #681).

---

packages/uniforms-antd/__tests__/SelectField.tsx
packages/uniforms-antd/src/SelectField.tsx

This PR introduces filtering `undefined` values inside `SelectField` to fix empty boxes.

Added filtering undefined values in array of SelectField (fixes #691).

---

CHANGELOG.md
packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts
packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/__tests__/ValidatedForm.tsx
packages/uniforms/__tests__/connectField.tsx
packages/uniforms/src/BaseForm.tsx
packages/uniforms/src/Bridge.ts
packages/uniforms/src/ValidatedForm.tsx

Let's start with a short flashback from #644:
> [...] Well, the first bridge ever was the SimpleSchema (the Meteor one), and its validator throws an error instead of returning it. It was perfectly fine, up to the point when we wanted to add `onSubmitSuccess`/`onSubmitFailure` and async validation. Of course, we managed to do so, but the solution is not very elegant.
This _not very elegant solution_ got implemented in #51. Why it's not elegant? Because it's redundant. There's no need for such hooks if one can simply add it directly to the `onSubmit`. Another problem (non-elegancy) is the asynchronous validation - invented in #17 and implemented in 4a56596f8a2e296f891316430cdba104cd21f8e6. It's weird and is using callbacks.
This PR introduces a new, clean flow (including …

Asyncified validate + submit flow

---

CHANGELOG.md
packages/uniforms/__tests__/connectField.tsx
packages/uniforms/src/connectField.tsx

Finally, with #720 and #721 merged, we can remove `includeInChain` flag from `connectField`. It was used only in the `NestField` and `ListField` family, and mostly because of the way how the old context API worked.

Removed includeInChain

---

CHANGELOG.md
packages/uniforms/src/AutoForm.tsx

The `modelSync` was introduced back in da56d32a9d0ee03e6a061a8b674492beac4b3fc6, without any additional comment. I remember it was required to make the async validation work at all. I've run some extensive testing and it looks like it's not the case in the current React version.
Performance-wise, this removes one complete re-render of the `AutoForm`, which is the most used form component.

Removed modelSync from AutoForm state.

---

CHANGELOG.md
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

This change fixes resolving `properties` and `required` fields in JSONSchema when combined with `allOf`/`anyOf`/`oneOf`.
_I've also fixed our lovely, long-standing typo._

Fixed resolving parallel properties in JSONSchema (fixes #746).

---

CHANGELOG.md
packages/uniforms-antd/__tests__/RadioField.tsx
packages/uniforms-antd/__tests__/SelectField.tsx
packages/uniforms-bootstrap3/__tests__/RadioField.tsx
packages/uniforms-bootstrap3/__tests__/SelectField.tsx
packages/uniforms-bootstrap3/src/RadioField.tsx
packages/uniforms-bootstrap3/src/SelectField.tsx
packages/uniforms-bootstrap4/__tests__/RadioField.tsx
packages/uniforms-bootstrap4/__tests__/SelectField.tsx
packages/uniforms-bootstrap4/src/RadioField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx
packages/uniforms-material/__tests__/RadioField.tsx
packages/uniforms-material/__tests__/SelectField.tsx
packages/uniforms-material/src/SelectField.tsx
packages/uniforms-semantic/__tests__/RadioField.tsx
packages/uniforms-semantic/__tests__/SelectField.tsx
packages/uniforms-semantic/src/RadioField.tsx
packages/uniforms-semantic/src/SelectField.tsx
packages/uniforms-unstyled/__tests__/RadioField.tsx
packages/uniforms-unstyled/__tests__/SelectField.tsx
packages/uniforms-unstyled/src/RadioField.tsx
packages/uniforms-unstyled/src/SelectField.tsx

This change fixes #753. As reported there, our [escape function](https://github.com/vazco/uniforms/blob/b0724e397d24fe4743de6c46487c4497f1de0a7e/packages/uniforms-material/src/SelectField.tsx#L135) (basically Base64) breaks on special characters (like diacritics). I've added `encodeURIComponent` to the pipeline to mitigate this issue.

Fixed escaping special characters

---

CHANGELOG.md
packages/uniforms-antd/src/DateField.tsx
packages/uniforms-antd/src/HiddenField.tsx
packages/uniforms-antd/src/SelectField.tsx
packages/uniforms-antd/src/wrapField.tsx
packages/uniforms-bootstrap3/src/HiddenField.tsx
packages/uniforms-bootstrap3/src/gridClassName.ts
packages/uniforms-bootstrap4/src/HiddenField.tsx
packages/uniforms-bootstrap4/src/gridClassName.ts
packages/uniforms-bridge-simple-schema-2/src/register.ts
packages/uniforms-bridge-simple-schema/src/register.ts
packages/uniforms-material/src/HiddenField.tsx
packages/uniforms-semantic/src/HiddenField.tsx
packages/uniforms-unstyled/src/HiddenField.tsx
packages/uniforms/__tests__/filterDOMProps.ts
packages/uniforms/src/filterDOMProps.ts
packages/uniforms/src/types.ts

This change enhances `filterDOMProps` return type from `Partial<T>` to `Omit<T, keyof FilterDOMProps>`. In short, this allows us to properly exclude all filtered props, including the ones in the user app. New props have to be registered in the type as well:
```ts
declare module 'uniforms' {
interface FilterDOMProps {
customPropToFilter: never;
}
}
filterDOMProps.register('customPropToFilter');
```
This showed a few unnecessarily passed props.

Improved filterDOMProps return type

---

packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/src/AutoForm.tsx

This change should fix the regression introduced in #739. Due to the removal of `modelSync`, `AutoForm` was no longer resolving `changed` and `changedMap` correctly, effectively not tracking `changed` states at all. I've fixed that, added test for that, ~and fixed other tests, as they were using shared form instance~ (I've moved that directly to v3 branch).
Once more, thanks to @mvgijssel for https://github.com/vazco/uniforms/pull/739#issuecomment-656643894!

Fixed changed state of AutoForm

---

packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/src/AutoForm.tsx

The fix made in #765 broke the validation of `AutoForm`, as reported in #769. This change fixes that, by removing an obsolete `onValidate` override in `AutoForm`.

Fixed AutoForm validation (fixes #769).

---

packages/uniforms-antd/__tests__/BoolField.tsx
packages/uniforms-antd/__tests__/DateField.tsx
packages/uniforms-antd/__tests__/ErrorField.tsx
packages/uniforms-antd/__tests__/ErrorsField.tsx
packages/uniforms-antd/__tests__/ListAddField.tsx
packages/uniforms-antd/__tests__/ListDelField.tsx
packages/uniforms-antd/__tests__/LongTextField.tsx
packages/uniforms-antd/__tests__/wrapField.tsx
packages/uniforms-antd/src/BoolField.tsx
packages/uniforms-antd/src/DateField.tsx
packages/uniforms-antd/src/ErrorField.tsx
packages/uniforms-antd/src/ErrorsField.tsx
packages/uniforms-antd/src/ListAddField.tsx
packages/uniforms-antd/src/ListDelField.tsx
packages/uniforms-antd/src/ListField.tsx
packages/uniforms-antd/src/ListItemField.tsx
packages/uniforms-antd/src/LongTextField.tsx
packages/uniforms-antd/src/NestField.tsx
packages/uniforms-antd/src/RadioField.tsx
packages/uniforms-antd/src/SubmitField.tsx
packages/uniforms-antd/src/wrapField.tsx

This PR closes #773 by updating the AntD styles of the `ListField` component to match the newest version.

Update AntD ListField styles.

---

CHANGELOG.md
packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
reproductions/schema/graphql-schema.tsx

As reported and discussed in #781, #784, and #786 , current `GraphQLBridge` is not well-typed. It got better with #784, but it was still _weird_. This change reviews this behavior, leading to a cleaner implementation and a clean `GraphQLType` as an input.
There is one breaking change, but I think no one was actually using that - the second argument of `getField` got removed. It means, that `field.type` prop will be `GraphQLNonNull<T>` instead of `T` for non-nullable types.

Reworked GraphQLBridge.getField (closes #786).

---

packages/uniforms-bootstrap4/__tests__/SelectField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx

#785
This PR will fix issue #785 and probably #793, the problem was in a [Spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) in the ``SelectField`` for bootstrap4, before pass props to ``wrapField`` few properties were removed from props, that is why in ``wrapField`` there were undefined.

#785 class name for select field

---

CHANGELOG.md
packages/uniforms/__tests__/connectField.tsx
packages/uniforms/src/useField.tsx

This change fixes a bug reported in #816 as well as adds a broad set of tests for `label` handling. We should do the same for `placeholder`, but this will come separately.

Fixed non-string labels (fixes #816).

---

packages/uniforms-antd/__tests__/wrapField.tsx
packages/uniforms-antd/src/wrapField.tsx

I built a custom field that I want to pass validateStatus='success' to AntD's Form.Item so I can give fast feedback when the data is entered in the correct format.  
This pull requests adds a default validateStatus prop to antd's wrapField that the error prop can still override.

Allow passing antd's validateStatus prop to wrapField for custom fields

---

CHANGELOG.md
packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/src/BaseForm.tsx

This change fixes #832 by asynchronizing autosave. This has one positive side effect - autosave is now batched.

Asynchronized autosave (fixes #832).

---

packages/uniforms-material/src/RadioField.tsx

Since `RadioField` is using Material's `RadioGroup` this change would allow users to specify the `row` property for the group (changing the orientation from vertical to horizontal).
From Material's [RadioGroup API](https://material-ui.com/components/radio-buttons/):
> To lay out the buttons horizontally, set the row prop: <RadioGroup row />.

Adds row support to uniforms-material RadioField

---

docs/migrating-2-to-3.md
website/docusaurus.config.js
website/sidebars.json

I've added all the notes from #808 to the website. Right now it's under the _Getting Started_ section and I'm not 100% sure if it's good. Also, I've enabled `hideableSidebar` to make the migration guide more readable.

Added migration guide (closes #808).

---

CHANGELOG.md
packages/uniforms-antd/__tests__/NumField.tsx
packages/uniforms-antd/src/NumField.tsx

This change solves #856, unifying `NumField` behavior across themes. In short, `NumField` in `uniforms-antd` uses the `InputNumber` component, which keeps input value in an internal state, syncing it back on blur. It stays like this, but now it'll revert to the default value on blur (the value will be removed from `model`).

Unified NumField behavior (fixes #856).

---

packages/uniforms-antd/__tests__/ListField.tsx
packages/uniforms-antd/src/ListField.tsx

This PR introduces ListField error stylings in uniforms-antd. 
Based on https://github.com/vazco/uniforms/issues/844.
No-error styling for comparison:

Added error styling for ListField in uniforms-antd (closes #844).

---

CHANGELOG.md
packages/uniforms-antd/package.json
packages/uniforms-bootstrap3/package.json
packages/uniforms-bootstrap4/package.json
packages/uniforms-bridge-graphql/package.json
packages/uniforms-bridge-json-schema/package.json
packages/uniforms-bridge-simple-schema-2/package.json
packages/uniforms-bridge-simple-schema/package.json
packages/uniforms-material/package.json
packages/uniforms-semantic/package.json
packages/uniforms-unstyled/package.json
packages/uniforms/package.json

This change configures [`sideEffects`](https://webpack.js.org/guides/tree-shaking/) in all packaged in order to let bundlers do better at tree shaking.

Configured sideEffects (closes #843).

---

docs/api-bridges.md

I've added some comments to cover problems with `allOf`/`anyOf`/`oneOf` discussed in https://github.com/vazco/uniforms/issues/863.

Added note about JSONSchemaBridge (closes #863).

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

As @michael-vasyliv mentioned in #880, our [`CONTRIBUTING.md`](https://github.com/vazco/uniforms/blob/master/.github/CONTRIBUTING.md) did not mention how to set up the project locally. I updated all of the relevant files: contributing guidelines, pull request template, and issue templates (including the new UX of it).

Updated contributing guidelines.

---

website/lib/presets.ts

AJV has a new "strict" mode and therefore complains on unknown properties on the schema. Luckily, you can specify additional kewords with `keywords: string[]`
or with
`ajv.addKeyword('uniforms');`
Before you open a pull request, please check if a similar one already exists or has been closed before. Detailed information about the process of contributing can be found in [CONTRIBUTING.md](https://github.com/vazco/uniforms/blob/master/.github/CONTRIBUTING.md).
Do link all relevant issues and pull requests. If there is none, please do file an issue first to discuss it upfront.

fix(Playground): JSONSchema example does allow `uniforms` property

---

CHANGELOG.md
packages/uniforms-semantic/src/SelectField.tsx

This change implements variant 2. of fixing SelectField styling issue reported and described in https://github.com/vazco/uniforms/issues/873#issuecomment-784039502.

Fixed SelectField style in uniforms-semantic (fixes #873).

---

CHANGELOG.md
packages/uniforms-bridge-simple-schema-2/package.json
packages/uniforms-bridge-simple-schema/package.json

As reported in #888, changes made in #870 were _slightly_ incomplete, resulting in an error:
```
Invalid definition for name field: "uniforms" is not a supported property
```
This change adds missing `sideEffect` files.

Added missing sideEffect files (fixes #888).

---

website/docusaurus.config.js

Added GTM tracking by [plugin-google-gtag](https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) which is available in previously installed preset `@docusaurus/preset-classic`.

Added tracking to the uniforms website.

---

CHANGELOG.md
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

This PR fixes #909 by handling `JSONSchemaBridge` errors with top-level fields containing spaces.

Fixed handling of white spaces in JSONSchemaBridge (fixes #909).

---

packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/src/BaseForm.tsx

As reported in #920, the autosave timeout was not cleared on unmount. This PR fixes that as well as corrects the tests.

Fixed leaking timeout (fixes #920).

---

docs/api-context-data.md
docs/api-helpers.md

Added `submitted` context data documentation Context data and Helpers page in API Reference.

Added `submitted` context data documentation (closes #914).

---

packages/uniforms-bootstrap3/src/wrapField.tsx
packages/uniforms-bootstrap4/src/BoolField.tsx
packages/uniforms-bootstrap4/src/DateField.tsx
packages/uniforms-bootstrap4/src/LongTextField.tsx
packages/uniforms-bootstrap4/src/NumField.tsx
packages/uniforms-bootstrap4/src/RadioField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx
packages/uniforms-bootstrap4/src/TextField.tsx
packages/uniforms-bootstrap4/src/wrapField.tsx
packages/uniforms-bootstrap5/src/BoolField.tsx
packages/uniforms-bootstrap5/src/DateField.tsx
packages/uniforms-bootstrap5/src/LongTextField.tsx
packages/uniforms-bootstrap5/src/NumField.tsx
packages/uniforms-bootstrap5/src/RadioField.tsx
packages/uniforms-bootstrap5/src/SelectField.tsx
packages/uniforms-bootstrap5/src/TextField.tsx
packages/uniforms-bootstrap5/src/wrapField.tsx

This PR introduces new style for successfully validated fields in Bootstrap themes (requested in #899)
I tried to stay consistent with current success styles, here are some examples from the playground:

Added success field style in Bootstrap themes (closes #899).

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

As mentioned in #923 in the newest version of Ajv the JSON Schema errors structure has been changed, so I adjusted the error `dataPath` with the fallback for previous Ajv versions.

Add Ajv v8 support in uniforms-bridge-json-schema (closes #923).

---

packages/uniforms-antd/__tests__/AutoFields.tsx
packages/uniforms-antd/src/AutoFields.tsx
packages/uniforms-bootstrap3/__tests__/AutoFields.tsx
packages/uniforms-bootstrap3/src/AutoFields.tsx
packages/uniforms-bootstrap4/__tests__/AutoFields.tsx
packages/uniforms-bootstrap4/src/AutoFields.tsx
packages/uniforms-bootstrap5/__tests__/AutoFields.tsx
packages/uniforms-bootstrap5/src/AutoFields.tsx
packages/uniforms-material/__tests__/AutoFields.tsx
packages/uniforms-material/src/AutoFields.tsx
packages/uniforms-semantic/__tests__/AutoFields.tsx
packages/uniforms-semantic/src/AutoFields.tsx

Added a possibility to pass 'showInlineError' to `AutoFields` in all themes except uniforms-unstyled, which was requested in #827.
I didn't come up with the idea of how to provide the possibility to pass all (or most) props to children `AutoField`. We just have to move them to a common property object and pass them to children, which precludes nice UX mentioned by @Floriferous because the interface differs from the `AutoField`. On the other hand, we have to provide an API to configure the `AutoFields` container component, so we have a override with the child `AutoField`, or we have to move this API to a common prop object - which is breaking change.
Therefore I introduce a minimal change in `AutoFields` allowing you to pass 'showInlineError' prop, and I want you to share your thoughts.

Add 'showInlineError' property to AutoFields (closes #827).

---

packages/uniforms/__tests__/joinName.ts
packages/uniforms/src/joinName.ts

This PR optimizes the `joinName` helper without affecting its functionality. On the presented benchmark, the performance improved from 217ms to 79ms (best time out of 25 runs).
<details>
<summary>Benchmark</summary>
```ts
describe('benchmark', () => {
it.each(Array.from({ length: 25 }, (_, x) => x + 1))('is fast %i', () => {
expect(true).toBe(true);
for (let index = 0; index < 5000; ++index) {
joinName(null);
joinName(null, 'a');
joinName(null, 'a', 'b');
joinName(null, 'a', 'b', null);
joinName(null, 'a', 'b', null, 0);
joinName(null, 'a', 'b', null, 1);
joinName(['a'], 'b');
joinName('a', ['b']);
joinName('', 'a', 'b');
joinName('a', '', 'b');
joinName('a', 'b', '');
joinName('a', null, 'b');
joinName('a', false, 'b');
joinName('a', undefined, 'b');
joinName(0, 'a', 'b');
joinName('a', …
```

Optimized joinName.

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

Fixed a bug where a field with no computed required subfields gets an empty 'required' prop. The same situation occurs with the 'properties'.

Added conditional properties and required field assignment in uniforms-bridge-json-schema (closing #919).

---

packages/uniforms/src/filterDOMProps.ts

**TL;DR; `filterDOMProps` is twice as fast now!**
This PR optimizes `filterDOMProps`. The benchmark I created consisted of two parts: one where 70%-100% of props were removed and the other where only 0%-20% were removed. Based on one of our apps, an average % of removed props is \~76%.
Additionally, the new version results in a smaller bundle as no lodash functions are used.
And finally, I rearranged the code a little to make sure that it'll appear as `filterDOMProps` instead of `filter` in error and profiler traces.
---
<details>
<summary>921ms + 394ms = 1315ms</summary>
```tsx
function filter<T extends object>(props: T) {
return pickBy(props, filterOne) as Omit<T, FilterDOMPropsKeys>;
}
```
</details>
<details>
<summary>606ms + 166ms = 772ms</summary>
```tsx
function filter<T extends …
```

Optimized `filterDOMProps`.

---

packages/uniforms-bootstrap3/src/DateField.tsx
packages/uniforms-bootstrap3/src/NestField.tsx
packages/uniforms-bootstrap3/src/RadioField.tsx
packages/uniforms-bootstrap3/src/SelectField.tsx
packages/uniforms-bootstrap4/src/DateField.tsx
packages/uniforms-bootstrap4/src/NestField.tsx
packages/uniforms-bootstrap4/src/RadioField.tsx
packages/uniforms-bootstrap4/src/SelectField.tsx
packages/uniforms-bootstrap5/src/DateField.tsx
packages/uniforms-bootstrap5/src/NestField.tsx
packages/uniforms-bootstrap5/src/RadioField.tsx
packages/uniforms-bootstrap5/src/SelectField.tsx
packages/uniforms-material/src/DateField.tsx
packages/uniforms-material/src/NestField.tsx
packages/uniforms-material/src/SelectField.tsx
packages/uniforms-semantic/src/DateField.tsx
packages/uniforms-semantic/src/NestField.tsx
packages/uniforms-semantic/src/RadioField.tsx
packages/uniforms-semantic/src/SelectField.tsx
packages/uniforms-unstyled/src/DateField.tsx
packages/uniforms-unstyled/src/RadioField.tsx
packages/uniforms-unstyled/src/SelectField.tsx
packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/__tests__/connectField.tsx
packages/uniforms/__tests__/randomIds.ts
packages/uniforms/__tests__/useField.tsx
packages/uniforms/src/useField.tsx
tsconfig.json

This PR targets to improve our test coverage. Hopefully, we'll reach 100% once again! To do so, I:
* Added `/* istanbul ignore next */` to our `btoa` and `global` polyfills.
* Configured `tsconfig.json` for `target: 'ESNext'` due to https://github.com/istanbuljs/nyc/issues/727.
* Added and/or updated unit tests.
* This actually highlighted a slight regression with handling `label={null}`. Nice!
* Removed unnecessary optional chaining.

Improved test coverage

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

This PR adds support for `object` fields without `properties` in `JSONSchemaBridge`, closing #934.

Added support for objects without properties (closes #934).

---

packages/uniforms/src/changedKeys.ts

This is the third and probably the last PR focused on optimizing one hottest functions, at least for now. Here I focused on `changedKeys`. On the benchmark I prepared, the time dropped from 626ms down to 247ms, which makes almost 60% improvement. Additionally, we no longer rely on `xorWith`, making the bundle _slightly_ smaller.
The only downside is that the implementation is now _slightly_ more complex, but I find it more verbose than the current one.
<details>
<summary>Benchmark</summary>
```tsx
describe('benchmark', () => {
it.each(Array.from({ length: 25 }, (_, x) => x + 1))('is fast %i', () => {
expect(true).toBe(true);
for (let index = 0; index < 5000; ++index) {
changedKeys('a', [], []);
changedKeys('a', [1], [1]);
changedKeys('a', [1, 2], [1, 2]);
changedKeys('a', new Date(10), …
```

Optimized `changedKeys`.

---

packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts

This PR fixes #950 as well as unifies the implementations of `getErrorMessages` across all bridges.

Unified `getErrorMessages` across bridges (fixes #950).

---

packages/uniforms-material/src/DateField.tsx

Improved DateField label in Material-UI theme.
Before:
After:

Improved DateField label in Material-UI theme.

---

packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts

Encouraged by the previous performance-oriented PRs (#935, #939, ad #953) as well as the one with unifying bridges logic (#956), I went one step further and done it for all the bridges. Now, this not only brings better performance but also simplifies and unifies their code. Bundles are also a little bit smaller than before.
Performance-wise, I focused on `JSONSchemaBridge`, as it has the most complex `getProps` of all the bridges. As I changed the `getField` as well, I measured `getProps` both with and without `memoize`ing `getField`. Overall, the new implementation is faster without cache than the old one with caching!
|     | with `memoize`  | without `memoize` |
| - | - | - |
| old | 523ms | 834ms |
| new | 195ms | 404ms |
<details>
<summary>Benchmark</summary>
```ts
import { …
```

Optimized and unified bridges logic.

---

packages/uniforms-antd/__tests__/SelectField.tsx
packages/uniforms-material/__tests__/SelectField.tsx
packages/uniforms-material/src/SelectField.tsx
packages/uniforms/src/types.ts

This PR aims to improve the `Override` type as suggested in https://github.com/vazco/uniforms/issues/951#issuecomment-836944631. It revealed a few unnecessary props in the `omit` call as well as some other quirks of `SelectField` in `uniforms-material`.
If possible, @aburtsev, please do check this code.

Improved field type inference (fixes #951).

---

.github/workflows/CI.yml

Add [dependencies duplication](https://docs.npmjs.com/cli/v7/commands/npm-dedupe) and [npm vulnerabilities](https://docs.npmjs.com/cli/v7/commands/npm-audit) reports to the CI workflow.
The CI run on PR to master branch will produce a warning if there are some possible fixes spotted.
The dependencies duplication report is checked by the `npm dedupe` command, while the vulnerabilities report by the `npm audit fix`.
Example warning in the GH action:
And in the workflow logs:

Add dependencies duplication and npm vulnerabilities reports to the CI workflow.

---

packages/uniforms-material/src/DateField.tsx
packages/uniforms-material/src/LongTextField.tsx
packages/uniforms-material/src/NumField.tsx
packages/uniforms-material/src/TextField.tsx

The previous type was only relevant for the "standard" variant of TextField. This PR changes the used type to the more general TextField one.
Fixes #987

Adjusted uniforms-material's TextField type.

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts

This PR adds recursive `$ref` resolution in JSON Schema Bridge. Previously, only the first `$ref` was resolved so `$ref` pointing to another `$ref` caused errors. Also added tests for this case.

Implemented recursive `$ref` resolution (fixes #1006).

---

packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts

Adjusted `getInitialValue` in both `SimpleSchemaBridge` and `SimpleSchema2Bridge`. The logic now follows more closely `JSONSchemaBridge`'s implementation. Also added a few tests to both bridges.

Fixed SimpleSchema bridges not returning default values for objects and arrays.

---

docs/examples-custom-fields.mdx
docs/faq.md

As said in #1009, the `autoField` prop is not as useful and easy to use as the `AutoField.componentDetectorContext`. In this PR, I've added a note about that in the docs.

Updated documentation about custom AutoField (#1009).

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/package.json
packages/uniforms-bridge-json-schema/src/index.ts
packages/uniforms-bridge-json-schema/src/register.ts

This PR closes #981 by registering `minCount` and `maxCount` in `filterDOMProps` when `JSONSchemaBridge` is imported.

Register minCount and maxCount in `filterDOMProps` of JSONSchema

---

docs/api-context-data.md
docs/api-forms.md
docs/faq.md

This PR adds small sections about new property `formRef` accessible in the context and how to use it.
Updated sections include:
- Context API reference
- Forms methods reference
- FAQ: How can I reset my form state?

Add `formRef` to documentation

---

.eslintrc.json
docs/api-helpers.md
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
packages/uniforms/__tests__/joinName.ts
packages/uniforms/src/joinName.ts

In this pull request, I've extended the `joinName` helper to make it work with "complex" field names. There are a lot of possible names that are impossible for uniforms at the moment - most importantly the ones with dots in names (see #963).
Most importantly, this change is backward compatible for all schemas with alphanumeric fields only (I believe it covers more than 99% of projects). When it comes to the rest, like the ones with fields called `/` or `[`, it may not be the case (it probably will with most of them; I still have to test it).
The point of this change is that `joinName` correctly understands JSON Path-like names. The rules are simple and very similar to the ones in JavaScript:
* `a` works as before, accessing top-level fields.
* `a.b` works as before, accessing objects' …

Implemented handling of complex field names.

---

.prettierrc.js
.prettierrc.json
docs/api-bridges.md
docs/examples-custom-bridge.md
docs/examples-custom-fields.mdx
docs/examples-custom-form.md
docs/faq.md
docs/installation.mdx
docs/tutorials-creating-custom-field.mdx
docs/tutorials-using-predefined-fields.mdx
tsconfig.json
website/components/Playground.tsx

Instead of duplicating a prettier config, it's imported from the `eslint-config-package` settings.

Imported prettier settings from eslint-config-vazco package

---

packages/uniforms/src/connectField.tsx

While testing #1091, I've noticed that some `kind='leaf'` fields, like `ListAddField`, are unnecessarily rendering the `Provider` component. It doesn't make sense, as there's nothing in the subtree that will use the adjusted context.
In the most common situation, i.e., `AutoField` rendering the field, it'd be skipped due to [this check](https://github.com/vazco/uniforms/blob/8cbb12516490c88d0ab0a71e2a7d467f92f4ae2f/packages/uniforms/src/createAutoField.tsx#L39-L41). However, when being rendered directly, they actually did render the `Provider` component. With this PR it's no longer the case.

Optimized `connectField` for leaf fields.

---

website/pages-parts/LandingPage/CommercialServices.tsx

This PR fixes the link under the `Check Form Builder in action` button. Clicking on both image and button in Form Builder section should open the same link with tracking.

Fixing tracking URL for Form Builder

---

.github/labeler.yml
.github/workflows/labeler.yml

To make triaging issues easier, I configured an automatic PR labeler. In the future, we could mimic a similar behavior in the `.github/CODEOWNERS` file if needed, e.g., when we'll have dedicated people for a given theme.

Configured PRs labeler

---

CHANGELOG.md
packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts

As reported in #1112, there are cases where using an empty object for the initial value (`getInitialValue` on a bridge) causes problems with the invariants we have. To fix that, I made it work in the same way as we work with arrays, i.e., resolve all subfields recursively.

Implemented recursive `getInitialValue` for objects (fixes #1112).

---

docs/faq.md
packages/uniforms-antd/package.json
packages/uniforms-bootstrap3/package.json
packages/uniforms-bootstrap4/package.json
packages/uniforms-bootstrap5/package.json
packages/uniforms-material/package.json
packages/uniforms-mui/package.json
packages/uniforms-semantic/package.json
packages/uniforms-unstyled/package.json
packages/uniforms/package.json

As described in [#1109](https://github.com/vazco/uniforms/issues/1109#issuecomment-1152271810), we've decided to make v18 a valid peer dependency with a note in the FAQ.

Added support for React 18 (closes #1109).

---

.github/workflows/CI.yml

As we discussed at the internal planning meeting ([card](https://github.com/orgs/vazco/projects/1#card-72596364)) we want to simplify and unify the ci workflow steps, so I created the [open-standards](https://github.com/vazco/open-standards) repo under the [Vazco](https://github.com/vazco) organization for workflows like npm dedupe and vulnerability checks.
This PR introduces a change to use workflows from [open-standards](https://github.com/vazco/open-standards) repo.
The reusable workflows have to be run as standalone jobs (what distinguishes them from official actions), and we have to deal with its consequences: 
1. We have to run checkout and node setup steps 2 times additionally.
2. We can run both actions only once per workflow run, not like it was - once every node matrix run (6 …

Use reusable workflows

---

packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
reproductions/schema/json-schema.tsx

This PR closes #1131 by extending behavior of `JSONSchemaBridge.getError` which now correctly returns errors for the fields with dots in their names.
The problem was that `Ajv` provides the `error.instancePath` in a "non-escaped way" for field names with dots.
```js
// Example schema
{
type: 'object',
properties: {
'nested.minLength': {
type: 'string',
minLength: 5,
default: 'Horse',
},
}
```
Uniforms would escape this field name into `["nested.minLength"]` but the `error.instancePath` would be `/nested.minLength`.
The fix uses `joinName.unescape` to unescape individual parts of the `name` and compare it to the `path` created from `error.instancePath`.

JSONSchemaBridge: Get errors for fields with dots

---

packages/uniforms-bootstrap3/__tests__/DateField.tsx
packages/uniforms-bootstrap3/src/DateField.tsx
packages/uniforms-bootstrap4/__tests__/DateField.tsx
packages/uniforms-bootstrap4/src/DateField.tsx
packages/uniforms-bootstrap5/__tests__/DateField.tsx
packages/uniforms-bootstrap5/src/DateField.tsx
packages/uniforms-material/__tests__/DateField.tsx
packages/uniforms-material/src/DateField.tsx
packages/uniforms-mui/__tests__/DateField.tsx
packages/uniforms-mui/src/DateField.tsx
packages/uniforms-semantic/__tests__/DateField.tsx
packages/uniforms-semantic/src/DateField.tsx
packages/uniforms-unstyled/__tests__/DateField.tsx
packages/uniforms-unstyled/src/DateField.tsx

Fixes #1138
Unified the implementation of date type logic across `DateField`s in themes. The only theme that was not adjusted was `antd` due to the fact that this is handled by a separate prop which is `showTime` that is already implemented. `antd` does not accept a `type` prop like the native date input does.
to do:
<details>
<summary>Screenshots</summary>
tested for this playground schema
```
new SimpleSchema2Bridge(
new SimpleSchema({
date: {
type: Date,
defaultValue: new Date(),
uniforms: {
type: 'date',
},
},
date2: {
type: Date,
defaultValue: new Date(),
},
})
)
```
unstyled
semantic
mui
material
bootstrap5
bootstrap4
bootstrap3
</details>

Unified implementation of DateField type handling.

---

docs/api-bridges.md
docs/faq.md
packages/uniforms/src/useForm.ts

Extended the current invariant message and added an entry to the FAQ.

Improved documentation for useForm error.

---

packages/uniforms/__tests__/BaseForm.tsx
packages/uniforms/__tests__/ValidatedForm.tsx
packages/uniforms/src/BaseForm.tsx

In this pull request, I fixed https://github.com/vazco/uniforms/issues/1152. There are at least 4 places where we'd need to check, whether or not we actually perform `setState` after the component gets unmounted. Instead, I overridden it to hide the React warning. Mostly because React no longer will raise it in the newer versions anyway (https://github.com/facebook/react/pull/22114).

Fixed unmounted `setState` warning (fixes #1152).

---

.github/labeler.yml
package-lock.json
package.json
packages/uniforms-bridge-zod/README.md
packages/uniforms-bridge-zod/__tests__/ZodBridge.ts
packages/uniforms-bridge-zod/__tests__/index.ts
packages/uniforms-bridge-zod/package.json
packages/uniforms-bridge-zod/src/ZodBridge.ts
packages/uniforms-bridge-zod/src/index.ts
packages/uniforms-bridge-zod/src/register.ts
packages/uniforms-bridge-zod/tsconfig.cjs.json
packages/uniforms-bridge-zod/tsconfig.esm.json
tsconfig.build.json
tsconfig.global.json
website/lib/presets.ts
website/lib/schema.ts
website/package.json

In this pull request, I added a new package: `uniforms-bridge-zod`, closing #1159. The implementation is really straightforward and documented in a step-by-step tutorial on my blog: [_"On uniforms Integration With Zod"_](https://radekmie.dev/blog/on-uniforms-integration-with-zod/).
Open topics:
1. **How to switch between sync and async validation?** Zod allows both, but before you actually run it, you don't know if it's going to be async or not. Doing it async by default is not ideal either, as it results in multiple renders for sync schemas.
* We can handle it with an option passed to the `ZodBridge` constructor.
2. **Is `ZodError` the only accepted error format?** I think it does - it's well documented and typed. But maybe we should handle others as well?
3. **How to implement …

Added Zod integration (closes #1159)

---

docs/tutorials-basic-uniforms-usage.mdx
docs/tutorials-using-predefined-fields.mdx
website/pages-parts/Tutorial/GuestSchema.ts
website/pages-parts/Tutorial/GuestSchema2.ts
website/pages-parts/Tutorial/GuestSchema3.ts
website/pages-parts/Tutorial/GuestSchema4.ts

This PR closes #1145 by adding warnings about Ajv strict keywords to the tutorial.
- Added warning (caution) [admonitions](https://docusaurus.io/docs/next/markdown-features/admonitions) to [_Basic uniforms usage_](https://uniforms.tools/docs/tutorials-basic-uniforms-usage/) and [_Using predefined fields_](https://uniforms.tools/docs/tutorials-using-predefined-fields/) about Ajv strict keywords
- Modified `GuestSchema`(s) to use Ajv [utility types](https://ajv.js.org/guide/typescript.html#utility-types-for-schemas)
<details>
<summary>Click to see screenshots...</summary>
</details>

Documentation: Add warnings about Ajv strict keywords to tutorial

---

docs/migrating-2-to-3.md

This PR adds `includeInChain` and how to migrate it to the migration guide from v2 to v3.

Add `includeInChain` to the breaking changes list of migration guide v2 to v3

---

docs/api-fields.md
docs/api-forms.md
docs/examples-custom-fields.mdx
docs/migrating-3-to-4.md
docs/uth-autofield-algorithm.md
packages/uniforms-antd/__tests__/AutoFields.tsx
packages/uniforms-antd/src/AutoFields.tsx
packages/uniforms-bootstrap3/__tests__/AutoFields.tsx
packages/uniforms-bootstrap3/src/AutoFields.tsx
packages/uniforms-bootstrap4/__tests__/AutoFields.tsx
packages/uniforms-bootstrap4/src/AutoFields.tsx
packages/uniforms-bootstrap5/__tests__/AutoFields.tsx
packages/uniforms-bootstrap5/src/AutoFields.tsx
packages/uniforms-material/__tests__/AutoFields.tsx
packages/uniforms-material/src/AutoFields.tsx
packages/uniforms-mui/__tests__/AutoFields.tsx
packages/uniforms-mui/src/AutoFields.tsx
packages/uniforms-semantic/__tests__/AutoFields.tsx
packages/uniforms-semantic/src/AutoFields.tsx
packages/uniforms-unstyled/__tests__/AutoFields.tsx
packages/uniforms-unstyled/src/AutoFields.tsx
packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/__tests__/QuickForm.tsx
packages/uniforms/src/QuickForm.tsx
website/sidebars.json

In this PR the autoField prop is removed from QuickForm and AutoForm.
Closes https://github.com/vazco/uniforms/issues/980.
Note: reopened for Hacktoberfest contribution.

Remove autoField prop from QuickForm and AutoForm

---

package.json

Single quotes were not parsed correctly and always reported that there are no files to check on Windows command shell. Using double quotes instead makes it work on the relevant shell environments.

Adjusted prettier command to work on Windows command shell.

---

docs/api-fields.md
docs/api-forms.md
docs/faq.md

- Fixed typos
- Replaced legacy ref with `useRef`
In reality, if you use the `useForm` without passing in the type (for example, to `AutoForm`), you won't have it typed correctly - you won't be able to call, for example, `formRef.current.reset()`. An explicit type needs to be given to access the methods of the referenced element.

Update uniforms docs

---

packages/uniforms-bridge-graphql/__tests__/GraphQLBridge.ts
packages/uniforms-bridge-graphql/src/GraphQLBridge.ts
packages/uniforms-bridge-json-schema/__tests__/JSONSchemaBridge.ts
packages/uniforms-bridge-json-schema/src/JSONSchemaBridge.ts
packages/uniforms-bridge-simple-schema-2/__tests__/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema-2/src/SimpleSchema2Bridge.ts
packages/uniforms-bridge-simple-schema/__tests__/SimpleSchemaBridge.ts
packages/uniforms-bridge-simple-schema/src/SimpleSchemaBridge.ts
packages/uniforms-bridge-zod/src/ZodBridge.ts
packages/uniforms/src/Bridge.ts
packages/uniforms/src/useField.tsx

In this pull request, I removed the second argument from `Bridge.getProps`, which is the same as we did with `getInitialValue` in #1185. The immediate benefit is that it becomes memoizable (and thus yields better performance), but also it wasn't really used for anything else than the `options`/`allowedValues`+`transform` handling, which we'll move to the components anyway via #806. (If you'll read the tests I removed you'll see they weren't really helpful.)

Removed props from `Bridge.getProps`

---

packages/uniforms-bootstrap5/__tests__/ListAddField.tsx
packages/uniforms-bootstrap5/__tests__/ListDelField.tsx
packages/uniforms-bootstrap5/src/ListAddField.tsx
packages/uniforms-bootstrap5/src/ListDelField.tsx
packages/uniforms-bootstrap5/src/ListItemField.tsx
reproductions/index.html
website/lib/styles.tsx

In this pull request, I changed the `ListAddField` and `ListDelField` components in the Bootstrap 5 theme to use `button`s instead of `div`s, together with button-native styles.
I also updated the CDN link to the latest CSS version, and improved layouting in `ListItemField` (lefthand side is now as wide as it needs, not 1/12).

Fixed Bootstrap 5 ListField controls (closes #1226).

---

docs/api-forms.md

This PR was inspired by the question asked in the discussion https://github.com/vazco/uniforms/discussions/1283.
- Added explicit example of asynchronous validation
- Added missing `return` at the end of the existing example
- Explained what `onValidate` should return to specify valid and invalid state

Extend Asynchronous validation docs with explicit example

---

docs/uth-autofield-algorithm.md

The previous docs on overriding the `AutoForm` confused me, so I rephrased it slightly.

Rephrase the AutoField algorithm docs

---

packages/uniforms-mui/__tests__/NestField.tsx

#1346
- Migrated MUI NestField tests to RTL
- Material NestField tests weren't changed. They will be removed entirely in the #1338.

Migrated `NestField` tests to @testing-library/react

---

packages/uniforms-mui/__tests__/SelectField.tsx
packages/uniforms-mui/__tests__/index.ts
packages/uniforms/__suites__/SelectField.tsx

Scope of this PR:
- enable MUI SelectField suite tests
- modify suite tests to pass in the MUI theme
- mostly filter out non `HTMLInputElement`s
- skip if it doesn't pass and there is no clear way to fix it
- remove local tests duplicated by the suites
The local tests that cover the same area as the suites with the new "filter" were not removed, as I'm not sure if it is the correct approach. I want to ask you for your opinion on that.

Enable mui SelectField suite tests

---

packages/uniforms-bridge-zod/src/ZodBridge.ts

Closes #1331
- Unwrap field if it is `ZodOptional`
Tested with:
- `z.string().array().optional()`
- `z.array(z.string()).optional()`
- other fields in the playground (All Fields (Zod))

Fixed optional array fields (Zod bridge)

---

packages/uniforms-antd/src/LongTextField.tsx
packages/uniforms-antd/src/TextField.tsx
packages/uniforms-bootstrap4/src/LongTextField.tsx
packages/uniforms-bootstrap4/src/TextField.tsx
packages/uniforms-bootstrap5/src/LongTextField.tsx
packages/uniforms-bootstrap5/src/TextField.tsx
packages/uniforms-mui/src/LongTextField.tsx
packages/uniforms-mui/src/TextField.tsx
packages/uniforms-semantic/src/LongTextField.tsx
packages/uniforms-semantic/src/TextField.tsx
packages/uniforms-unstyled/src/LongTextField.tsx
packages/uniforms-unstyled/src/TextField.tsx
packages/uniforms/__suites__/LongTextField.tsx
packages/uniforms/__suites__/TextField.tsx

Closes #1332
- Deleting input from `TextField` and `LongTextField` sets `undefined` instead of empty string in the model
- This behavior is already implemented in other fields ([playground](https://uniforms.tools/playground/#?N4IgDgTgpgzlAuIBcICCAbdACAYgSynQBMYsAKALQHsiBKEAGnAirBmVAEMBXeKmTgDcoyAGad0cJjz4DhAEUKcAnsgCMABg1MieAQCN0UImIlSQ6TvsLJ4EblCZhLAYygALKsSgRTkxyDQnEQA8gB26KpI4v5MMJ4A7gCSEXhhUACiECy-0WYBnDDKYS7hAMrc-gC2eIh5sSCFxaVhAGoSeESc8CL15jAu7lBVnMgg6QlY1EQAQhCdAOZQZMAAOmFYWANDI0hYAF4AdFT6AFZQLvAr65u3WD0AHvB7RzB2aQtktIc1YWQATN9WPA8FQwhIvgwbncsGFuFUXoc4VVrBAvj80gCgWAQWCIbQoRtbgBfWjrUkgYlMeA7XogOAjMIglyUoA) with optional `TextField` and `NumField`)

Blank `TextField` and `LongTextField`

---

docs/migrating-3-to-4.md

This PR updates the migration guide for uniforms from v3 to v4 to include information on the changes to constructors in all bridges.
This change addresses issue #1360.

Add bridge constructor changes to v4 migration guide.

---

docs/api-forms.md
packages/uniforms/__tests__/AutoForm.tsx
packages/uniforms/src/AutoForm.tsx

Closes #1359.
This PR extends `AutoForm.onChangeModel` to provide additional information `details: { key, value, previousValue }`.
- `key` is the changed key
- `value` is the new value
- `previousValue` is the value before the change

Extend `onChangeModel` - add details about what changed

---

.github/workflows/CI.yml
package-lock.json
package.json
packages/uniforms/src/BaseForm.tsx
tsconfig.json

<details>
<summary>1. List `@types/node` package</summary>
```
npm ls @types/node
uniforms-repository@ /Users/adrianmucha/uniforms
├─┬ @types/jest@26.0.20
│ ├─┬ jest-diff@26.6.2
│ │ └─┬ pretty-format@26.6.2
│ │   └─┬ @jest/types@26.6.2
│ │     └── @types/node@17.0.18 deduped
│ └─┬ pretty-format@26.6.2
│   └─┬ @jest/types@26.6.2
│     └── @types/node@17.0.18 deduped
├─┬ jest-environment-jsdom@29.7.0
│ ├─┬ @jest/environment@29.7.0
│ │ └── @types/node@17.0.18 deduped
│ ├─┬ @jest/fake-timers@29.7.0
│ │ └── @types/node@17.0.18 deduped
│ ├─┬ @jest/types@29.6.3
│ │ └── @types/node@17.0.18 deduped
│ ├─┬ @types/jsdom@20.0.1
│ │ └── @types/node@17.0.18 deduped
│ ├── @types/node@17.0.18
│ ├─┬ jest-mock@29.7.0
│ │ └── @types/node@17.0.18 deduped
│ └─┬ jest-util@29.7.0
│   └── @types/node@17.0.18 …
```

Turborepo typescript fix build

---

jest.config.js
packages/uniforms-antd/__tests__/DateField.tsx
packages/uniforms-antd/__tests__/SelectField.tsx
packages/uniforms-antd/__tests__/index.ts
packages/uniforms-antd/__tests__/wrapField.tsx
packages/uniforms-antd/package.json
packages/uniforms-antd/src/DateField.tsx
packages/uniforms-antd/src/ListDelField.tsx
packages/uniforms-antd/src/NumField.tsx
packages/uniforms-antd/src/SelectField.tsx
packages/uniforms-antd/src/SubmitField.tsx
packages/uniforms-antd/src/TextField.tsx
packages/uniforms/__suites__/NumField.tsx
packages/uniforms/__suites__/SelectField.tsx
pnpm-lock.yaml

Based on the `update-react` branch. Update React to v18 in the `uniforms-antd` package. Updating AntD to v5 is required.

Update react 18 antd5

---

packages/uniforms-bridge-zod/__tests__/ZodBridge.ts
packages/uniforms-bridge-zod/src/ZodBridge.ts
packages/uniforms-mui/__tests__/SelectField.tsx
packages/uniforms/__suites__/RadioField.tsx
packages/uniforms/__suites__/SelectField.tsx

- Removed setting initial value for enum type (`SelectField`). This is the same behavior as we have for example in the `SimpleSchema2Bridge`
- Update tests. As the `SelectField` tests will be changed (#1351), I will do it after the PR merge. For this reason, I open this as a draft.

Removed setting initial value for enum type

---

CHANGELOG.md
packages/uniforms-antd/package.json
packages/uniforms-bootstrap4/package.json
packages/uniforms-bootstrap5/package.json
packages/uniforms-bridge-json-schema/package.json
packages/uniforms-bridge-simple-schema-2/package.json
packages/uniforms-bridge-zod/package.json
packages/uniforms-mui/package.json
packages/uniforms-semantic/package.json
packages/uniforms-unstyled/package.json
packages/uniforms/package.json
pnpm-lock.yaml

- Updated uniforms packages to `4.0.0-beta.1`
- Moved `uniforms` from `dependencies` to `peerDependencies`. Added also workspace version to `devDependencies` for pnpm
- Updated changelog with latest changes
- Updated changelog with missing `4.0.0-alpha.6` version changes

Update packages & changelog

---

packages/uniforms-antd/package.json
pnpm-lock.yaml

Minimum supported React version in AntD is `16.9.0` ([link](https://github.com/ant-design/ant-design/blob/3f8943e2744f41f6c1434225b8f72d2813b1b722/package.json#L104)). In this pull request, I updated `peerDependencies` to change `16.8.0` to `16.9.0`.

Updated supported version of React in AntD theme

---

packages/uniforms-mui/package.json
pnpm-lock.yaml
reproductions/package.json

- Updated `@mui/material` to `v6` in the `uniforms-mui` theme
- Updated `@mui/material` in the `reproductions` directory
- `MUI v6` doesn't introduce breaking changes that has impact on our theme ([MUI migration guide](https://mui.com/material-ui/migration/upgrade-to-v6/))
- only breaking changes affecting testing ([docs](https://mui.com/material-ui/migration/upgrade-to-v6/#breaking-changes-affecting-testing)) could interfere with our tests, but I didn't notice any additional warnings
<details>
<summary>Screenshot (all fields example from playground)</summary>
</details>

Update MUI to v6

---

website/docs/getting-started/custom-theme.md

- added page about adding custom theme to docs

Added custom theme tutorial docs

---

packages/uniforms/src/useForm.ts
website/docs/getting-started/faq.mdx

- Added FAQ page to Getting Started section in docs
- Changed link accordingly

Added FAQ to docs

---

packages/uniforms-antd/src/LongTextField.tsx
packages/uniforms-antd/src/TextField.tsx
packages/uniforms-bootstrap4/src/LongTextField.tsx
packages/uniforms-bootstrap4/src/TextField.tsx
packages/uniforms-bootstrap5/src/LongTextField.tsx
packages/uniforms-bootstrap5/src/TextField.tsx
packages/uniforms-mui/src/LongTextField.tsx
packages/uniforms-mui/src/TextField.tsx
packages/uniforms-semantic/src/LongTextField.tsx
packages/uniforms-semantic/src/TextField.tsx
packages/uniforms-unstyled/src/LongTextField.tsx
packages/uniforms-unstyled/src/TextField.tsx
packages/uniforms/__suites__/LongTextField.tsx
packages/uniforms/__suites__/TextField.tsx

- reverted change introduced during alpha/beta of uniforms v4
- we should also consider removing `undefined` from `NumField` and other fields

Empty string if text field is empty instead of undefined
